spring:
  application:
    name: ${APP_NAME:TRI-AUTH-DEV-APP}
    version: ${APP_VERSION:0.0.2}

  main:
    banner-mode: console

  config:
    import:
      - optional:classpath:application-dev-env.properties
      - optional:classpath:application-liquibase.yaml
      - optional:classpath:application-db.yaml

server:
  servlet:
    context-path: ${CONTEXT_PATH_PREFIX:/tri-auth-dev-api/v1}


