spring:
  liquibase:
    url: ${DB_URL:jdbc:postgresql://[::1]:5432/mydatabase?currentSchema=tri&user=myuser&password=${DB_PASSWORD:secret}}
    change-log: ${LIQUIBASE_MASTER_FILE_PATH:classpath:db/changelog/changelog-master.xml}
    default-schema: ${LIQUIBASE_SCHEMA:TRI}
    liquibase-schema: ${LIQUIBASE_SCHEMA:TRI}
    enabled: ${LIQUIBASE_ENABLED:true}
    database-change-log-table: ${LIQUIBASE_DATABASE_CHANGELOG_TABLE:DATABASECHANGELOG}
    database-change-log-lock-table: ${LIQUIBASE_DATABASE_CHANGELOG_LOCK_TABLE:DATABASECHANGELOGLOCK}
    analytics-enabled: ${LIQUIBASE_ANALYTICS_ENABLED:true}
    show-summary-output: log
    user: ${LIQUIBASE_USER:myuser}
    clear-checksums: ${CLEAR_CHECKSUMS:false}