#!/usr/bin/env bash
#GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_DB TO $POSTGRES_USER;
#GRANT ALL PRIVILEGES ON DATABASE $APP_DB TO $POSTGRES_USER;
printf "Initial Db Script Starting \n"
set -e
psql -v ON_ERROR_STOP=1  --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<EOSQL || { echo "script down !" ; exit 1; }
   CREATE USER $APP_USER WITH PASSWORD '$APP_PASSWORD';
   CREATE DATABASE $APP_DB;
   GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_DB TO $APP_USER;
   GRANT ALL PRIVILEGES ON DATABASE $APP_DB TO $APP_USER;
EOSQL

psql -v ON_ERROR_STOP=1 --username "$APP_USER" --dbname "$APP_DB" <<EOSQL || { echo "script down !" ; exit 1; }
   CREATE SCHEMA IF NOT EXISTS $APP_SCHEMA AUTHORIZATION $APP_USER;
   GRANT USAGE ON SCHEMA $APP_SCHEMA TO $APP_USER;
EOSQL

printf "POSTGRES USER: %s GRANT ON DATABASES %s, %s AUTHORITY GIVEN TO %s FOR SCHEMA: %s", "$APP_USER" "$POSTGRES_DB" "$APP_DB" "$APP_USER" "$APP_SCHEMA";

